var PostConstants = {
  POSTS_RECEIVED: "POSTS_RECEIVED",
  POST_RECEIVED: "POST_RECEIVED",
  COMMENT_RECEIVED: "COMMENT_RECEIVED",
  LIKE_RECEIVED: "LIKE_RECEIVED",
  LIKE_REMOVED: "LIKE_REMOVED"
};

module.exports = PostConstants;
