var UserIndexConstants = {
  USERS_RECEIVED: "USERS_RECEIVED",
  USER_RECEIVED: "USER_RECEIVED",
  FOLLOW_RECEIVED: "FOLLOW_RECEIVED",
  FOLLOW_REMOVED: "FOLLOW_REMOVED"
};

module.exports = UserIndexConstants;
